artworks = [
    {
        "id": 1,
        "title": "Echoes of Silence",
        "medium": "Oil on Canvas",
        "edition": "Original",
        "dimensions": "80x100 cm",
        "sold": False,
        "history": "Created during a period of isolation, reflecting inner stillness.",
        "artist_name": "Lena Kristoff",
        "date": "2018",
        "starting_price": 1200,
        "art_movement": "Contemporary",
        "image_path": "https://i0.wp.com/images.metmuseum.org/CRDImages/as/original/DP130155.jpg?w=1290&ssl=1",
    },
    {
        "id": 2,
        "title": "Fragments of Time",
        "medium": "Acrylic on Canvas",
        "edition": "Limited Edition",
        "dimensions": "60x90 cm",
        "sold": True,
        "history": "Inspired by urban decay and memory.",
        "artist_name": "Aron Sigurdsson",
        "date": "2020",
        "starting_price": 900,
        "art_movement": "Abstract Expressionism",
        "image_path": "https://media.timeout.com/images/103166739/750/562/image.jpg",
    },
    {
        "id": 3,
        "title": "Northern Lights",
        "medium": "Digital Print",
        "edition": "Edition of 50",
        "dimensions": "50x70 cm",
        "sold": False,
        "history": "Captures the fleeting beauty of Icelandic skies.",
        "artist_name": "Eva Bjornsdottir",
        "date": "2021",
        "starting_price": 500,
        "art_movement": "Digital Art",
        "image_path": "https://i0.wp.com/images.metmuseum.org/CRDImages/as/original/DP130155.jpg?w=1290&ssl=1",
    },
    {
        "id": 4,
        "title": "Golden Horizon",
        "medium": "Oil on Canvas",
        "edition": "Original",
        "dimensions": "100x120 cm",
        "sold": True,
        "history": "Painted after a journey through southern Europe.",
        "artist_name": "Marco Del Rio",
        "date": "2017",
        "starting_price": 2000,
        "art_movement": "Impressionism",
        "image_path": "https://i0.wp.com/images.metmuseum.org/CRDImages/as/original/DP130155.jpg?w=1290&ssl=1",
    },
    {
        "id": 5,
        "title": "Broken Geometry",
        "medium": "Mixed Media",
        "edition": "Original",
        "dimensions": "70x70 cm",
        "sold": False,
        "history": "Explores chaos through structured forms.",
        "artist_name": "Klara Jensen",
        "date": "2019",
        "starting_price": 1100,
        "art_movement": "Cubism",
        "image_path": "https://i0.wp.com/images.metmuseum.org/CRDImages/as/original/DP130155.jpg?w=1290&ssl=1",
    },
    {
        "id": 6,
        "title": "Still Water",
        "medium": "Watercolor",
        "edition": "Original",
        "dimensions": "40x60 cm",
        "sold": False,
        "history": "A calm lake painted at dawn.",
        "artist_name": "Hiro Tanaka",
        "date": "2016",
        "starting_price": 600,
        "art_movement": "Minimalism",
        "image_path": "https://i0.wp.com/images.metmuseum.org/CRDImages/as/original/DP130155.jpg?w=1290&ssl=1",
    },
    {
        "id": 7,
        "title": "Urban Pulse",
        "medium": "Spray Paint on Canvas",
        "edition": "Original",
        "dimensions": "90x110 cm",
        "sold": True,
        "history": "Inspired by street life and graffiti culture.",
        "artist_name": "Jay Carter",
        "date": "2022",
        "starting_price": 1500,
        "art_movement": "Street Art",
        "image_path": "https://i0.wp.com/images.metmuseum.org/CRDImages/as/original/DP130155.jpg?w=1290&ssl=1",
    },
    {
        "id": 8,
        "title": "Dream Sequence",
        "medium": "Oil on Canvas",
        "edition": "Original",
        "dimensions": "85x95 cm",
        "sold": False,
        "history": "A surreal journey through subconscious imagery.",
        "artist_name": "Elena Rossi",
        "date": "2015",
        "starting_price": 1800,
        "art_movement": "Surrealism",
        "image_path": "https://i0.wp.com/images.metmuseum.org/CRDImages/as/original/DP130155.jpg?w=1290&ssl=1",
    },
    {
        "id": 9,
        "title": "Mechanical Soul",
        "medium": "Mixed Media",
        "edition": "Original",
        "dimensions": "75x100 cm",
        "sold": True,
        "history": "Combines human emotion with industrial elements.",
        "artist_name": "Victor Hale",
        "date": "2021",
        "starting_price": 1300,
        "art_movement": "Futurism",
        "image_path": "https://i0.wp.com/images.metmuseum.org/CRDImages/as/original/DP130155.jpg?w=1290&ssl=1",
    },
    {
        "id": 10,
        "title": "Bloom",
        "medium": "Acrylic on Canvas",
        "edition": "Edition of 20",
        "dimensions": "60x60 cm",
        "sold": False,
        "history": "Represents growth and transformation.",
        "artist_name": "Sofia Martinez",
        "date": "2023",
        "starting_price": 750,
        "art_movement": "Modernism",
        "image_path": "https://i0.wp.com/images.metmuseum.org/CRDImages/as/original/DP130155.jpg?w=1290&ssl=1",
    },
    {
        "id": 11,
        "title": "Shattered Reflections",
        "medium": "Glass and Resin",
        "edition": "Original",
        "dimensions": "50x80 cm",
        "sold": False,
        "history": "Explores identity through fractured surfaces.",
        "artist_name": "Noah Berg",
        "date": "2019",
        "starting_price": 1400,
        "art_movement": "Contemporary",
        "image_path": "https://i0.wp.com/images.metmuseum.org/CRDImages/as/original/DP130155.jpg?w=1290&ssl=1",
    },
    {
        "id": 12,
        "title": "Silent Forest",
        "medium": "Oil on Canvas",
        "edition": "Original",
        "dimensions": "100x140 cm",
        "sold": True,
        "history": "Depicts untouched wilderness in muted tones.",
        "artist_name": "Anna Petrov",
        "date": "2014",
        "starting_price": 2100,
        "art_movement": "Realism",
        "image_path": "https://i0.wp.com/images.metmuseum.org/CRDImages/as/original/DP130155.jpg?w=1290&ssl=1",
    },
    {
        "id": 13,
        "title": "Electric Dreams",
        "medium": "Digital Art",
        "edition": "Edition of 100",
        "dimensions": "1920x1080 px",
        "sold": False,
        "history": "Inspired by cyberpunk aesthetics.",
        "artist_name": "Kai Nakamura",
        "date": "2022",
        "starting_price": 400,
        "art_movement": "Cyberpunk",
        "image_path": "https://i0.wp.com/images.metmuseum.org/CRDImages/as/original/DP130155.jpg?w=1290&ssl=1",
    },
    {
        "id": 14,
        "title": "Fading Memories",
        "medium": "Charcoal on Paper",
        "edition": "Original",
        "dimensions": "30x50 cm",
        "sold": False,
        "history": "A study of memory loss and nostalgia.",
        "artist_name": "Isabella Moretti",
        "date": "2018",
        "starting_price": 550,
        "art_movement": "Expressionism",
        "image_path": "https://i0.wp.com/images.metmuseum.org/CRDImages/as/original/DP130155.jpg?w=1290&ssl=1",
    },
    {
        "id": 15,
        "title": "Gravity Shift",
        "medium": "Mixed Media",
        "edition": "Original",
        "dimensions": "80x120 cm",
        "sold": True,
        "history": "Challenges perception of space and balance.",
        "artist_name": "Lukas Schmidt",
        "date": "2020",
        "starting_price": 1600,
        "art_movement": "Abstract",
        "image_path": "https://i0.wp.com/images.metmuseum.org/CRDImages/as/original/DP130155.jpg?w=1290&ssl=1",
    },
]
