# Generated by Django 6.0.4 on 2026-05-05 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('medium', models.CharField(max_length=255)),
                ('edition', models.CharField(max_length=255)),
                ('dimensions', models.CharField(max_length=255)),
                ('sold', models.BooleanField()),
                ('history', models.CharField(max_length=4096)),
                ('artist_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('starting_price', models.CharField(max_length=255)),
                ('art_movement', models.CharField(max_length=255)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.sellerprofilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='ArtWorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artvault.artwork')),
            ],
        ),
    ]
