# Generated by Django 6.0.4 on 2026-05-05 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvault', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artvault.artwork')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.buyerprofilemodel')),
            ],
        ),
    ]
