# Generated by Django 6.0.4 on 2026-05-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvault', '0002_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
