# Generated by Django 6.0.4 on 2026-05-05 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvault', '0003_alter_bid_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkimage',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='artvault.artwork'),
        ),
    ]
