# Generated by Django 6.0.4 on 2026-05-06 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvault', '0004_alter_artworkimage_artwork'),
        ('user', '0003_alter_buyerprofilemodel_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='user.sellerprofilemodel'),
        ),
    ]
