# Generated by Django 6.0.4 on 2026-05-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvault', '0005_alter_artwork_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkimage',
            name='image_path',
            field=models.ImageField(upload_to='media/artworks/'),
        ),
    ]
