# Generated by Django 6.0.4 on 2026-05-07 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artvault', '0006_alter_artworkimage_image_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artworkimage',
            old_name='image_path',
            new_name='image',
        ),
    ]
