# Generated by Django 6.0.4 on 2026-05-08 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvault', '0007_rename_image_path_artworkimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkimage',
            name='image',
            field=models.ImageField(upload_to='artworks/'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='artvault.artwork'),
        ),
    ]
