# Generated by Django 6.0.4 on 2026-05-08 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvault', '0008_alter_artworkimage_image_alter_bid_artwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='auction_end_date',
            field=models.DateField(default=datetime.date(2026, 5, 15)),
        ),
        migrations.AddField(
            model_name='artwork',
            name='auction_start_date',
            field=models.DateField(default=datetime.datetime(2026, 5, 8, 13, 23, 20, 728313, tzinfo=datetime.timezone.utc)),
        ),
    ]
