# Generated by Django 6.0.4 on 2026-05-11 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvault', '0009_artwork_auction_end_date_artwork_auction_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='auction_end_date',
            field=models.DateField(default=datetime.date(2026, 5, 18)),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='auction_start_date',
            field=models.DateField(default=datetime.datetime(2026, 5, 11, 10, 38, 55, 924971, tzinfo=datetime.timezone.utc)),
        ),
    ]
