# Generated by Django 6.0.4 on 2026-05-11 10:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvault', '0009_artwork_auction_end_date_artwork_auction_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtmovementArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('portrait', models.ImageField(upload_to='artmovements/portraits/')),
            ],
        ),
        migrations.AlterField(
            model_name='artwork',
            name='auction_end_date',
            field=models.DateField(default=datetime.date(2026, 5, 18)),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='auction_start_date',
            field=models.DateField(default=datetime.datetime(2026, 5, 11, 10, 57, 22, 793707, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Artmovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('artists', models.ManyToManyField(related_name='movements', to='artvault.artmovementartist')),
            ],
        ),
        migrations.CreateModel(
            name='ArtmovementArtwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='artworks/')),
                ('title', models.CharField(max_length=255, null=True)),
                ('artmovement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artvault.artmovement')),
                ('artmovement_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artvault.artmovementartist')),
            ],
        ),
    ]
