# Generated by Django 6.0.4 on 2026-05-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvault', '0010_alter_artwork_auction_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='auction_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='auction_start_date',
            field=models.DateField(),
        ),
    ]
