# Generated by Django 6.0.4 on 2026-05-11 20:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvault', '0010_artmovementartist_alter_artwork_auction_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artmovementartwork',
            name='artmovement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='artvault.artmovement'),
        ),
        migrations.AlterField(
            model_name='artmovementartwork',
            name='artmovement_artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='artvault.artmovementartist'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='auction_start_date',
            field=models.DateField(default=datetime.datetime(2026, 5, 11, 20, 5, 49, 279056, tzinfo=datetime.timezone.utc)),
        ),
    ]
