# Generated by Django 6.0.4 on 2026-05-12 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artvault', '0011_alter_artmovementartwork_artmovement_and_more'),
        ('artvault', '0011_alter_artwork_auction_end_date_and_more'),
    ]

    operations = [
    ]
