# Generated by Django 6.0.4 on 2026-05-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvault', '0012_merge_20260513_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='auction_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='auction_start_date',
            field=models.DateField(),
        ),
    ]
