# Generated by Django 6.0.4 on 2026-05-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artvault', '0012_merge_20260512_1328'),
        ('artvault', '0013_artwork_is_closed_alter_artwork_auction_end_date_and_more'),
    ]

    operations = [
    ]
