# Generated by Django 6.0.4 on 2026-05-06 12:38

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(blank=True, choices=[('card', 'Credit Card'), ('bank', 'Bank Transfer'), ('wire', 'Wire Transfer')], default='', max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('national_id', models.CharField(max_length=10)),
                ('street_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder_name', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=20)),
                ('card_cvv', models.CharField(max_length=20)),
                ('card_expiration', models.CharField(max_length=20)),
                ('shipping', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bids.shippingmodel')),
            ],
        ),
        migrations.CreateModel(
            name='BankTransferModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=4)),
                ('hb', models.CharField(max_length=2)),
                ('account', models.CharField(max_length=6)),
                ('shipping', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bids.shippingmodel')),
            ],
        ),
        migrations.CreateModel(
            name='WireTransferModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_bank', models.CharField(max_length=100)),
                ('routing_number', models.CharField(max_length=8)),
                ('account_number', models.CharField(max_length=12)),
                ('shipping', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bids.shippingmodel')),
            ],
        ),
    ]
