# Generated by Django 6.0.4 on 2026-05-11 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvault', '0011_alter_artwork_auction_end_date_and_more'),
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmodel',
            name='bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_details', to='artvault.bid'),
        ),
    ]
