# Generated by Django 6.0.4 on 2026-05-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_shippingmodel_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcardmodel',
            name='card_cvv',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='creditcardmodel',
            name='card_expiration',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='creditcardmodel',
            name='card_number',
            field=models.CharField(max_length=16),
        ),
    ]
