# Generated by Django 6.0.4 on 2026-05-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_alter_creditcardmodel_card_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcardmodel',
            name='card_cvv',
            field=models.CharField(max_length=4),
        ),
    ]
