# Generated by Django 6.0.4 on 2026-05-15 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_alter_creditcardmodel_card_cvv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcardmodel',
            name='shipping',
        ),
        migrations.RemoveField(
            model_name='shippingmodel',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='wiretransfermodel',
            name='shipping',
        ),
        migrations.DeleteModel(
            name='BankTransferModel',
        ),
        migrations.DeleteModel(
            name='CreditCardModel',
        ),
        migrations.DeleteModel(
            name='ShippingModel',
        ),
        migrations.DeleteModel(
            name='WireTransferModel',
        ),
    ]
