# Generated by Django 6.0.4 on 2026-05-15 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artvault', '0014_merge_20260514_1131'),
        ('bids', '0005_remove_creditcardmodel_shipping_and_more'),
        ('user', '0004_merge_20260508_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_datetime', models.DateTimeField(auto_now_add=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='artvault.artwork')),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='artvault.bid')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='user.buyerprofilemodel')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='user.sellerprofilemodel')),
            ],
        ),
    ]
