# Generated by Django 6.0.4 on 2026-05-06 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofilemodel',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profile', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='sellerprofilemodel',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to='user.profile'),
        ),
    ]
