# Generated by Django 6.0.4 on 2026-05-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofilemodel',
            name='profile_image',
            field=models.ImageField(upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='sellerprofilemodel',
            name='cover_photo',
            field=models.ImageField(upload_to='cover_photos/'),
        ),
        migrations.AlterField(
            model_name='sellerprofilemodel',
            name='logo',
            field=models.ImageField(upload_to='logos/'),
        ),
    ]
