# Generated by Django 6.0.4 on 2026-05-08 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_buyerprofilemodel_profile_image_and_more'),
        ('user', '0003_alter_buyerprofilemodel_profile_image_and_more'),
    ]

    operations = [
    ]
